build: Fix build with latest tree
Latest ell tree has introduced useful.h and main-private.h which are
required to build:

ell/cert-crypto.c:35:10: fatal error: useful.h: No such file or
directory
   35 | #include "useful.h"
         |          ^~~~~~~~~~
...